apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-star-battle
  namespace: default
spec:
  replicas: 1  # Default replica count
  selector:
    matchLabels:
      app: simple-star-battle
  template:
    metadata:
      labels:
        app: simple-star-battle
    spec:
      containers:
      - name: simple-star-battle
        image: public.ecr.aws/h2n4d7m6/simple-star-battle:latest
