apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-star-battle-app-dev
spec:
  destination:
    name: ''
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: gitops/overlays/dev
    repoURL: 'https://github.com/erdenayates/gitops-project'
    targetRevision: HEAD
  sources: []
  project: simple-star-battle-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

